# docker-compose.yml
version: "3"

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-02-07T08-17-33Z
  command: server --console-address ":9001" http://minio{1...5}/data-minio{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: adm1n_usr
    MINIO_ROOT_PASSWORD: K7MDENG
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./../data/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: adm1n
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: _1_p0sTgr3s!>DB

  grafana:
    image: grafana/grafana:8.0.4
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/custom.ini

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel
    volumes:
      - ./../data/redis:/data

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data-minio1-1:/data1
      - data-minio1-2:/data2

  nginx:
    image: nginx:stable-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1

volumes:
  data-minio1-1:
  data-minio1-2:
  data-minio2-1:
  data-minio2-2:
