# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/postgres/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: postgres

  motioneye:
    image: ccrisan/motioneye:dev-amd64
    restart: always
    volumes:
      - db-data:/var/motioneye/data
    ports:
      - "8765:8765"

volumes:
  db-data:
