# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/postgres/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: admin_
      POSTGRES_PASSWORD: 1_postgres!>DB

  grafana:
    image: grafana/grafana:8.0.4
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - db-data:/var/grafana/data

  prometeus:
    image: prom/prometheus
    restart: always
    ports:
     - "9090:9090"
    volumes:
      - db-data:/var/prometeus/data

volumes:
  db-data:
