# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./../data/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: adm1n
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: _1_p0sTgr3s!>DB

  grafana:
    image: grafana/grafana:8.0.4
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/custom.ini

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel
    volumes:
      - ./../data/redis:/data
