# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: admin_
      POSTGRES_PASSWORD: 1_postgres!>DB

  grafana:
    image: grafana/grafana:8.0.4
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/custom.ini

volumes:
  data:
